mounts:
- - 192.168.0.23:/mnt/VM/rancher-file-nfs
  - /mnt/
  - nfs4
  - ""
rancher:
  services:
    k3s-agent:
      command: agent --docker
      environment:
      - K3S_URL=https://192.168.0.10:6443
      - K3S_TOKEN=K10ad4e626089808e28f3fe87e7201cb0ca663f4ca33d4aee2856d8cbd41788b2fd::node:247506b228be6d4c5a6aec0ba3c15fca
      image: rancher/k3s:v0.8.0
      ipc: host
      net: host
      pid: host
      privileged: true
      volumes:
      - /var/lib/rancher/k3s:/var/lib/rancher/k3s:rshared
      - /var/lib/docker:/var/lib/docker:rshared
      - /var/run:/var/run
      - /run:/run